language: bash
sudo: required
services:
- docker
before_script:
- sudo apt-get update && sudo apt-get install git

script:
- make
after_success:
- make push_image
env:
  global:
  - secure: H+OcFlJketmPjlt+byfU63O3DaC2hLDR02m1PmS9+DUnr+0IcA5Z4wHzzPiTiD8d09Cg2FQWs0LqpEUWCOuqydMUKoXAEq18sjYoh/jsod0FXy1rEOptjBmrTRjctfyMWHsvtKcvthpoJ6TmlTZ/VvdggDDJ70+ZHh7mma8zYvmIeVSvAhH/Zw+GFzhc8S7PwW8zug1sUZbrtoqmOBar5INAVHqVRjXjsA4f5kNxAf4WXZnjvy8WQj6gOGc53GY3UqJAXxMkOAzCJ97wPE1g2l6aQPue8Pu0gJqhuIKhVvODiewkWrAvo9bwTDimf0gjwjq0D2282wYodBtINtBa2Le2nwBIXIqAmySINcZzX/P/vLeYofAlfIK1euX6kW3gadg73MyoLNfTMxa9tq5HS9NysUpdAxSN4AgQijk09hAO1oLHaCLf6aqHARlVlkRCNR4tLXzGWgl8O22pZDg5qfl7m1JJgtqdtgFfwlNX3QMwraghfzxbNgHahd6OpwJHS1/WER0TlkRWgJcEwotybCBjL0b2xBi+SvRDBq3nLVkQ2JuO5SZPHllsVUqgfO7UHQPZEBGbceVM3kAFWL6fnI5ExRUn3tX6KXuXbLGiy0LsUP+dDrtWacI7ed8GX26usq5+kOjmGjZ/RiXUplPX76HK2B4cpwedPrQHh9klWeI=
  - secure: HIgGOoZw9DZQnslHGjhG09pEMJRS8cp2YBJg/+R90zJ876+GqFvvCY+BjOGR2IOyyrrS6uT15K4SngnKZtujp/xZYmZqeNO5Lao1djpCGoUqmds1ueB+dyi8tc4g5RkyDVsWhJ5VQx02q94ScEtssn1JYyLr0tpgjduHTbNApzJ7wxJK3nWulcg2UCMta8i+aEzLdlEe7MpWLecXqrglN3YXM6q9d7WT4ZMbwLW3XRfgcvB3xJ9UHhcy/vcliP52iazjG2acFqQO9e/gt1AF6ThIwHTpsn9mDeSAK8QPrZc6DQR4fZwL8TJKMquoOm0/7AM/TO7b+Uz+pLG50zGryVA+zNyzBb2FQUh1sHdnfdVx/74pD0TadlD6zvJOGHyRa/HvuE2GegfqfXwZJWo7A19PU5NZzISk5JoRnXjjJNG9K9srnNhD5oDzmtfmU6T/8MOj4JYo/d69BYK9MgkpTmGCfBxrwQj2TtmM+/Gnrmawrrn+66ArbhgQ4xgPmltJKc8WSJcvuT5+loPCwkI2liPNCRE2rWt1v2ZXyDwsKVKv7KPMoYObP2HK3gBIhnoFvhhxMiOik5SJ/7/Ip5G4UqOXRO8GPo+RIJWTNrW40BTS0B+wpdl1SQeSAUzia5+w7o5GQihmi7InBriSYmnKTRvFsS2rBajltT38PzRMD90=
