language: bash
sudo: required
services:
- docker
before_script:
- sudo apt-get update && sudo apt-get install git
script:
- make
after_success:
- make push_image
env:
  global:
    secure: p8Iml9B//U9QoY5MAPYD/jjsLryLg4UyjYVZs+K9bTOiCv5HCIgeQrZNxSGNN98SuG4CrSOKXOsOmPQXCyVArufwqNFQJqwM1u9b3U225CcU9A1RDkF278vjzH5R0nW5iv/1jnXYMJqoTfh+CJmqM48T2oIvqZppRybookvTbTUUN5HmC0kKRLDmew0EcCGNLMxbPZmb5/h7uYikw/i7F/X0G7rxD1WsARPSrp8xso2GaMJBlNjUxS8RzcPWWomfDCyDPJWfBSJcqhiNwM5lNYMsbAAzZDODNKg+LaDE3aH1h5y89rW1bjNVGmi4j/991/AtRCghmyRItB1nKNkGI4LyvfUvMUICvmJRljjdidN9QSMnm7iyWkkaZUTOYFv7aU8n8AhSXvAMI2wWfloFliwjJNZFYgO7JpIzEaJZXGlqXaywm5nKFDroiffopQY2Y5Zk6CtCjqA5FRpdaznWtrXV2A8K+nKBlFcWUxhkRH4aTIap7c7rziIYTViRaijcfduOzQsPTffOOSqRsKA7rp2nVwm5Hfr4jCGGytAWaxrLgH/FlsjXfn6CBVFtDqM9RgOGJxpyaMjraA6CQQ1APwhtHpN1WselxRI9uI/nWtzsPPGPCi+AQzwD1uPx2BakENJAgPgVGOOf1q0imn+CI9599e0NgiPmCCy5kgdB9pA=
