language: bash
sudo: required
services:
- docker
before_script:
- sudo apt-get update && sudo apt-get install git
script:
- make
after_success:
- make push_image
env:
  global:
    secure: tdD7jfOcHeK3so7n2NHl9YY2u2FE0Nf/SIgI/FAlDjW4DFzpNPjTx5DYigCvnVxTVuS5yMHctStwfr1DUxgXs5ziizafCz3D2nB0gorVreC/0+FOBLWBkD4EWXScqtic9shH1ExhTY+uI9NVQzRYyTYVmE0wYsdSFVhek1m2bVyal92ffOkebFx1HGJ9x8QZ6HQ7TLmZ5UNumbNmUnVZqXyxoNB8ksUhwUEXVKeTWQykodrcF/VlXkZ9tGq9j3HtiiSvwu7/2AUOVSmIJS9Rw7mKdNMXQndwz4ChwBRqTj4j20wutfTKhufdNQwxDkfr+wnmcqD2FVNDG4CvntF/PUCNl84zILV4balHpo+EZwR/cndwnRWLt5LjXhwT8PFdqihvttDZxjnqbQYuO34sZqYMDjP+D6sXb8yvIe2QoeXuSg5BZ4TG2rcTPHn19NysD4mZB0d1e8ei14EczVHUcyBSECypjFy03fOzbKr3dIPCns+08T33A28S8jx6v6kYZeVoGTr+e9sIS6b9p/gcyGaoJqw3kVTqNoJh1zw1ccxX+BX2vZl/XlxFFjm2sPnd1eu3WHgM14ceCotWyQYivHistZh/dLVqkWarIKX4G4fWFhDurJBIJ/07y6ETQ4xG4T26BVovcKRNtbOOZBq4iVf+M1lKUFVIv1UNCOP6Fug=
    secure: qLjmHancCfjzI4CR44Xba0xkkNj2uzERQ6Ptn1NNT38quVGSU2tF4mGncJraAG3dPDU/NIj/syBNX7vx2k4hIL+NhBHweX37di4zrXiirZqebr2gsoR53l5dOOvnajnwiaxOk+dDQafc95iP3pUktcMTvlggxxY2yIg3qIMM0GQ4mQds3ogp8Uf64bEn8jQXpBHKrH91wHgXYs+5Nuzk4Wp4mBT8ogehNwB/sSJa28qJoIoZy4uBB6YNyP7aSVKPi4nBz7zItQm+PdxQiVzoWdSxP7aJ9h0QOXOzPjcKu/8X0XiAJhS6zNWcBaiD7hKQ0dj5EDiZx5GmBUsbrm30SFwELKN+lFGUnDxV/gevmovjb/UVRJYTXiHA/jqVQnj1Kzp245mbaP3q4IDafClE+gEVhVr9ajU9xTk8WRBOzUX0HjXQ4Hwyz7lYJ9/nK5dWRlHhxOARnWw7f6PyrdHlcSJpYQ4pd1ub2YhLP0T362TLaQLAXGx04sN3S9V2I/fh38hC5LC/L2WgxPG/DPowK17syzOcIQgIxJ8kyXd/kXXCzHJXS2kX8Em0YdbuLCXXVfnd3W9IP3jyeiKrynU4Lje6u7+B0beCuZu0XS5DLNi1fXiVzleMa6kr51UmuAprPtMOQcECXnhDdIOQvjQB7FumJjg0wu3VFTAlQjRGMy8=
