language: bash
sudo: required
services:
  - docker
before_script:
  - sudo apt-get update && sudo apt-get install git
script:
  - make
after_success:
  - make push_image
env:
  global:
  - secure: tdD7jfOcHeK3so7n2NHl9YY2u2FE0Nf/SIgI/FAlDjW4DFzpNPjTx5DYigCvnVxTVuS5yMHctStwfr1DUxgXs5ziizafCz3D2nB0gorVreC/0+FOBLWBkD4EWXScqtic9shH1ExhTY+uI9NVQzRYyTYVmE0wYsdSFVhek1m2bVyal92ffOkebFx1HGJ9x8QZ6HQ7TLmZ5UNumbNmUnVZqXyxoNB8ksUhwUEXVKeTWQykodrcF/VlXkZ9tGq9j3HtiiSvwu7/2AUOVSmIJS9Rw7mKdNMXQndwz4ChwBRqTj4j20wutfTKhufdNQwxDkfr+wnmcqD2FVNDG4CvntF/PUCNl84zILV4balHpo+EZwR/cndwnRWLt5LjXhwT8PFdqihvttDZxjnqbQYuO34sZqYMDjP+D6sXb8yvIe2QoeXuSg5BZ4TG2rcTPHn19NysD4mZB0d1e8ei14EczVHUcyBSECypjFy03fOzbKr3dIPCns+08T33A28S8jx6v6kYZeVoGTr+e9sIS6b9p/gcyGaoJqw3kVTqNoJh1zw1ccxX+BX2vZl/XlxFFjm2sPnd1eu3WHgM14ceCotWyQYivHistZh/dLVqkWarIKX4G4fWFhDurJBIJ/07y6ETQ4xG4T26BVovcKRNtbOOZBq4iVf+M1lKUFVIv1UNCOP6Fug=
  - secure: "dtdepOG7eBUqtT12Nlzznq0BhRvEoPT/95+K2y90Aq/DCgJ6WKkOAnBqoEsPljh362xKp8tVvIs7HJgJgQ5bMRyQbSwIiTQ8WNKk+7jjnW+YRGRt+U73veytklr3pMe5syq1mN830HEt2TAtv2WbzKSCeMHZONj8FNk7H+O4whh6bEsFDvZ+T/YtRx1I4wquxnrnXiSnV5IMqmPJo32oK8v37UIdJCMSOGsMUJac9ofs+yv2GCJBBrLUN1MIWibZ/RMITznu67/nrUtkMQZhKe9i8pbSh9ll2imAG7z0OO3s5fM/9Wnahyk6p+7ZGX7NEQqWZ4ofkHOFK242TFrmR1O+cS9I9L+LzN5KPOF+bvs9Ujszi0m8P7+CPt/n53bbDeR8936p9CTFoWDY5RHUQiYVTGM1jI6NADA79YRADbSskawtBu1+Qm3i0hnHwuZ87B0XPPNShrHcCu9thzA5yQd6bItcPCMYiCPSDGQtFmw9zpa+kRWXZpCV6lXp+fdxlIoacBxnVQI8qNHn/kwCpTP8bOd0OHmWMMOIm08D1vBla31a6OxyR4ww5jMJd3Aw1Yqw0bkbM1bUUeUdA7uLX/w6tEMeO3CkJSQxU6svwM/CUYpoVmy8/etDojX4xZOWqqJ60HUqPqccy5v6h5ae52HN7TI6X7eNg6kEfklWuA8="
